### ISSUE TITLE
Lust wage seems to interact poorly with monsters desummoned as a result of monsters dying

### ISSUE THREAD

**Issue by demogorgon22** [Chris-plus-alphanumericgibberish/dNAO#2100]
Killed the elder priest with lust active and it caused a bunch of "placing defunct monster onto map?" impossibles as it was presumably trying to push around some ants he'd summoned that had been desummoned as a result of killing him? Not sure.

**Comment by Chris-plus-alphanumericgibberish** [comment]
I forget if I fixed this already :(

**Comment by demogorgon22** [comment]
I feel like when I was running games on devel it was after this comment was made and that I was still seeing it. Ok, confirmed paniclog of a bunch of these impossibles at once that were probably a priests ants on March 24. I am going with no, it was not already fixed.
